In [37]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
import numpy as np

In [38]:
df = pd.read_csv(filepath_or_buffer = 'Breast_cancer_data.csv', sep = ",")
print(df.head())
#print(df.keys())

   mean_radius  mean_texture  mean_perimeter  mean_area  mean_smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   diagnosis  
0          0  
1          0  
2          0  
3          0  
4          0  


In [48]:

#df = df.astype({'0':'float'})
df_std = StandardScaler().fit_transform(df)
mean_vec = np.mean(df_std, axis = 0)
cov_mat = np.cov(df_std.T)
print(cov_mat)
eig_vals, eig_vecs = np.linalg.eig(cov_mat)
print(eig_vals)
print(eig_vecs)

[[ 1.00176056  0.32435193  0.99961207  0.98909547  0.17088151 -0.73131377]
 [ 0.32435193  1.00176056  0.33011322  0.32165099 -0.02342969 -0.41591626]
 [ 0.99961207  0.33011322  1.00176056  0.98824361  0.20764309 -0.74394299]
 [ 0.98909547  0.32165099  0.98824361  1.00176056  0.17734005 -0.71023205]
 [ 0.17088151 -0.02342969  0.20764309  0.17734005  1.00176056 -0.35919123]
 [-0.73131377 -0.41591626 -0.74394299 -0.71023205 -0.35919123  1.00176056]]
[3.83605507e+00 1.03578022e+00 8.30441853e-01 2.91095013e-01
 1.39212910e-03 1.57990892e-02]
[[-0.49492212 -0.06100523  0.23990282  0.15628968  0.70733665 -0.4111271 ]
 [-0.23293133 -0.47712714 -0.80420402  0.26697554  0.00629552 -0.00574548]
 [-0.49803542 -0.03130825  0.21411585  0.1620177  -0.70625281 -0.42437265]
 [-0.4911335  -0.05652924  0.24270798  0.21916641 -0.01119123  0.80531112]
 [-0.15022172  0.86522406 -0.36888285  0.30338288  0.02648406 -0.00190311]
 [ 0.434715   -0.1258555   0.23425459  0.85905342 -0.00394246 -0.04816356]]


In [50]:
eig_pairs = [(np.abs(eig_vals[i]), eig_vecs[:, i]) for i in range(len(eig_vals))]
eig_pairs.sort()
eig_pairs.reverse()
print(eig_pairs)

[(3.8360550723962623, array([-0.49492212, -0.23293133, -0.49803542, -0.4911335 , -0.15022172,
        0.434715  ])), (1.035780224036483, array([-0.06100523, -0.47712714, -0.03130825, -0.05652924,  0.86522406,
       -0.1258555 ])), (0.8304418527005263, array([ 0.23990282, -0.80420402,  0.21411585,  0.24270798, -0.36888285,
        0.23425459])), (0.2910950128598334, array([0.15628968, 0.26697554, 0.1620177 , 0.21916641, 0.30338288,
       0.85905342])), (0.01579908919182589, array([-0.4111271 , -0.00574548, -0.42437265,  0.80531112, -0.00190311,
       -0.04816356])), (0.001392129096763669, array([ 0.70733665,  0.00629552, -0.70625281, -0.01119123,  0.02648406,
       -0.00394246]))]


In [52]:
total = sum(eig_vals)
var_exp = [(i/total)*100 for i in sorted(eig_vals, reverse = True)]
print(var_exp)

[63.821888726452116, 17.232664535814934, 13.81637294475391, 4.843057038792772, 0.2628553796413913, 0.023161374544867115]


In [53]:
matrix_w = np.hstack((eig_pairs[0][1].reshape(6,1), 
                      eig_pairs[1][1].reshape(6,1),
                      eig_pairs[2][1].reshape(6,1)))

print('Matrix W:\n', matrix_w)

Matrix W:
 [[-0.49492212 -0.06100523  0.23990282]
 [-0.23293133 -0.47712714 -0.80420402]
 [-0.49803542 -0.03130825  0.21411585]
 [-0.4911335  -0.05652924  0.24270798]
 [-0.15022172  0.86522406 -0.36888285]
 [ 0.434715   -0.1258555   0.23425459]]


In [56]:
Y = df_std.dot(matrix_w)
print(Y)

[[-1.97568481  2.34730684  1.55883485]
 [-3.04023374 -0.65577132  1.54868585]
 [-3.1396354   0.52733517  0.07436711]
 ...
 [-1.88078266 -1.63646057 -1.18622084]
 [-4.08698311  0.09635452 -1.45913976]
 [ 2.97849615 -3.12926935 -0.80350587]]
